name: Android CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:

jobs:
  build-lint-unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Ktlint
        run: gradle ktlintCheck

      - name: Detekt
        run: gradle detekt

      - name: Unit tests
        run: gradle testDebugUnitTest

      - name: Build debug APK
        run: gradle assembleDebug

  instrumentation-tests:
    runs-on: macos-latest
    needs: build-lint-unit-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Compose instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_7
          script: gradle connectedDebugAndroidTest
